kind: Service
apiVersion: v1
metadata:
  name: my-python-website
spec:
  type: NodePort
  selector:
    app: python-website
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-website-deployment
  labels:
    app: python-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-website
      track: stable
  template:
    metadata:
      labels:
        app: python-website
        track: stable
    spec:
      containers:
      - name: python-website
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
